### ISSUE TITLE
Online multiplayer?

### ISSUE THREAD

**Issue by tnfssc** [RaviVanam/tic-tac-toe#1]
Is there an online multiplayer mode planned?

**Comment by RaviVanam** [comment]
> Is there an online multiplayer mode planned?

There is a plan to add player vs CPU mode.
Now that you asked, I realize it would be much cooler have a multiplayer mode.
Yes It's planned then

**Comment by RaviVanam** [comment]
This issue is being tracked in this project.

https://github.com/users/RaviVanam/projects/2/views/1
